AWSTemplateFormatVersion: '2010-09-09'
Description: 'function to process and store SES notifications'
Transform:
  - 'AWS::Serverless-2016-10-31'
Parameters: 
  DBHOST: 
    Type: String
  DBUSER: 
    Type: String
  DBPASSWORD: 
    Type: String
  DBPORT: 
    Type: Number
  DBDATABASE: 
    Type: String

Resources:
  SESTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      DisplayName: ses_topic
      TopicName: ses_topic
  Logger:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: 'A Lambda function that logs the payload of messages to a database'
      Runtime: nodejs12.x
      Handler: function.handler
      CodeUri: dist/
      Environment:
        Variables:
          DB_HOST: 
            Ref: "DBHOST"
          DB_USER:
            Ref: "DBUSER"
          DB_PASSWORD: 
            Ref: "DBPASSWORD"
          DB_PORT: 
            Ref: "DBPORT"
          DB_DATABASE: 
            Ref: "DBDATABASE"
      Events:
        SNSTopicEvent:
          Type: SNS
          Properties:
            Topic:
              Ref: "SESTopic"
      MemorySize: 128
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        