AWSTemplateFormatVersion: '2010-09-09'
Description: 'function to process and store SES notifications'
Transform:
  - 'AWS::Serverless-2016-10-31'
Resources:
  SESTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      DisplayName: ses_topic
      TopicName: ses_topic
  Logger:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: 'A Lambda function that logs the payload of messages to a database'
      Runtime: nodejs12.x
      Handler: dist/function.js
      CodeUri: dist/
      Environment:
        Variables:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
      Events:
        SNSTopicEvent:
          Type: SNS
          Properties:
            Topic: !Ref SESTopic
      MemorySize: 128
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        