name: Tests

on:
  push:
    branches:
      - staging
      - deploy
jobs:
  test_and_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm install
        npm run test
        npm run build
        aws cloudformation package --template template.yml --s3-bucket ${{ secrets.S3_BUCKET }} --output-template dist/template-export.yml
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.node-version }}
        path: dist/
        if-no-files-found: error
  deploy:
    runs-on: ubuntu-latest
    needs: test_and_build
    if: github.ref == 'refs/heads/deploy'
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Download Artifact
      uses: actions/download-artifact@v2
      path: ~/download/
      with:
        name: ${{ matrix.node-version }}
    - name: Display structure of downloaded files
      run: aws cloudformation deploy --capabilities CAPABILITY_IAM --template-file template-export.yml --stack-name seslogger
      working-directory: ~/download/    
