name: Tests

on:
  push:
    branches:
      - master
jobs:
  test_and_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm install
        npm run test
        npm run build
        aws cloudformation package --template template.yml --s3-bucket ${{ secrets.S3_BUCKET }} --output-template dist/template-export.yml
    - name: 
      uses: actions/upload-artifact@v2
      with:
        name: 
        path: |
          dist            